version: '3.4'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - retro-tool

  db_test:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - "postgres_test_data:/var/lib/postgresql/data"
    networks:
      - retro-tool

  api:
    build:
      context: ./
      target: dev
      dockerfile: .docker/node/Dockerfile
    container_name: 'retro-tool-api'
    volumes:
      - "./:/usr/src/app"
    ports:
      - 3333:3333
      - 9229:9229
    stdin_open: true
    depends_on:
      - db
    networks:
      - retro-tool

networks:
  retro-tool:
volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local
