name: API
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - name: Check Format
        run: yarn format:check api
      - name: Check Lint
        run: yarn lint api
      - name: Test
        run: yarn test api --codeCoverage --verbose
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: api
    env:
      TEST_DB_USER: root
      TEST_DB_PASSWORD: password
      TEST_DATABASE_HOST: mysql
      TEST_DATABASE_PORT: 33306
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
