name: E2E

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        name: Chrome
        with:
          browser: chrome
          command: yarn prisma db push --force-reset && yarn e2e
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:${{ job.services.postgres.ports[5432] }}/database?schema=public'
          TOKEN_SECRET: randomSecret123
          GITHUB_CLIENT_ID: randomClientId
          GITHUB_CLIENT_SECRET: randomClientSecret
          GITHUB_CALLBACK_URL: http://localhost:3333/auth/github/callback
          SPA_URL: http://localhost:4200
          COOKIE_DOMAIN: localhost
          NX_API_URL: http://localhost:3333
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/client-e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/client-e2e/videos
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: database
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
