name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    name: E2E
    env:
      TOKEN_SECRET: randomSecret123
      GITHUB_CLIENT_ID: randomClientId
      GITHUB_CLIENT_SECRET: randomClientSecret
      GITHUB_CALLBACK_URL: http://localhost:3333/auth/github/callback
      SPA_URL: http://localhost:4200
      COOKIE_DOMAIN: localhost
      NX_API_URL: http://localhost:3333
      USE_MOCK_AUTH: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - run: yarn prisma db push
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:${{ job.services.postgres.ports[5432] }}/database?schema=public'
      - run: ls -la apps/client-e2e/src/fixtures
      - run: yarn prisma migrate reset --force
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:${{ job.services.postgres.ports[5432] }}/database?schema=public'
      - uses: cypress-io/github-action@v2
        name: Chrome
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:${{ job.services.postgres.ports[5432] }}/database?schema=public'
        with:
          browser: chrome
          install: false
          command: yarn e2e
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/client-e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/client-e2e/videos
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: database
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
